services:
  tvlegal:
    build: .
    container_name: tvlegal
    environment:
      - PORT=8080
    volumes:
      - ./device.wvd:/app/device.wvd:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
